language: python
matrix:
  include:
   - python: 2.6
     env:
       - TOX_ENV=py26-1.4
       - TOX_ENV=py26-1.5
       - TOX_ENV=py26-1.6
   - python: 2.7
     env: TOXENV=py27-1.4,py27-1.5,py27-1.6
install:
  - pip install tox
script:
  - tox
